# Generated by Django 4.2.3 on 2023-08-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lootlegends', '0002_game_genre_media_post_user_userfavoritegames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegenre',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lootlegends.game'),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lootlegends.genre'),
        ),
        migrations.AlterField(
            model_name='gamepost',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lootlegends.game'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lootlegends.user'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='media_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lootlegends.media'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lootlegends.user'),
        ),
        migrations.AlterField(
            model_name='userfavoritegames',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lootlegends.game'),
        ),
        migrations.AlterField(
            model_name='userfavoritegames',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lootlegends.user'),
        ),
    ]
