# Generated by Django 4.2.3 on 2023-08-24 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lootlegends', '0003_alter_gamegenre_game_alter_gamegenre_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_cover_art',
        ),
        migrations.AddField(
            model_name='game',
            name='game_description',
            field=models.CharField(default='This should be here', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='game',
            name='game_rating',
            field=models.CharField(default='...', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ManyToManyField(through='lootlegends.UserFavoriteGames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='user_id',
            field=models.ManyToManyField(through='lootlegends.PostMedia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfavoritegames',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
