# Generated by Django 4.2.3 on 2023-08-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lootlegends', '0004_remove_game_game_cover_art_game_game_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_image',
            new_name='game_image_url',
        ),
    ]
