# Generated by Django 4.2.3 on 2023-08-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lootlegends', '0006_remove_game_game_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
    ]
