# Generated by Django 4.2.3 on 2023-08-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lootlegends', '0007_remove_game_game_rating_remove_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(through='lootlegends.GameGenre', to='lootlegends.genre'),
        ),
    ]
