# Generated by Django 4.2.3 on 2023-08-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lootlegends', '0008_game_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='posts',
        ),
    ]
