# Generated by Django 4.2.3 on 2023-08-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lootlegends', '0010_game_game_rating_game_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_rating',
        ),
    ]
