# Generated by Django 4.2.3 on 2023-08-28 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lootlegends', '0011_remove_game_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritegames',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lootlegends.game'),
        ),
        migrations.AlterField(
            model_name='userfavoritegames',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
